name: "personal_finances"

services:

  postgres:
    image: postgres:16-alpine
    container_name: finances_postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: finances_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superuser -d finances_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "finances_db_data:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    hostname: rabbitmq
    container_name: finances_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  finances_db_data:
  rabbitmq-data:
