"""add category_id fk in spendings

Revision ID: 0fd9019002c1
Revises: 8d2252dce3b9
Create Date: 2025-02-13 12:51:21.825526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0fd9019002c1"
down_revision: Union[str, None] = "8d2252dce3b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spendings", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f("fk_spendings_category_id_users_spending_categories"),
        "spendings",
        "users_spending_categories",
        ["category_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_spendings_category_id_users_spending_categories"),
        "spendings",
        type_="foreignkey",
    )
    op.drop_column("spendings", "category_id")
    # ### end Alembic commands ###
