"""drop spending categories

Revision ID: f0e27e103ec1
Revises: 7cc038632bf5
Create Date: 2025-02-13 12:10:00.668936

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f0e27e103ec1"
down_revision: Union[str, None] = "7cc038632bf5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint(
        "fk_spendings_category_id_spending_categories", "spendings", type_="foreignkey"
    )
    op.drop_column("spendings", "category_id")
    op.drop_constraint("uq_user_category", "users_spending_categories", type_="unique")
    op.drop_constraint(
        "fk_users_spending_categories_category_id_spending_categories",
        "users_spending_categories",
        type_="foreignkey",
    )
    op.drop_column("users_spending_categories", "category_id")

    op.drop_index("ix_spending_categories_name", table_name="spending_categories")
    op.drop_table("spending_categories")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spending_categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.VARCHAR(length=50), autoincrement=False, nullable=False
            ),
        sa.PrimaryKeyConstraint("id", name="pk_spending_categories"),
    )
    op.create_index(
        "ix_spending_categories_name", "spending_categories", ["name"],
        unique=True
    )

    op.add_column(
        "users_spending_categories",
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_users_spending_categories_category_id_spending_categories",
        "users_spending_categories",
        "spending_categories",
        ["category_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "uq_user_category", "users_spending_categories", ["user_id", "category_id"]
    )
    op.add_column(
        "spendings",
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_spendings_category_id_spending_categories",
        "spendings",
        "spending_categories",
        ["category_id"],
        ["id"],
    )

    # ### end Alembic commands ###
